package nodegit;
@:jsRequire("nodegit", "Commit") extern class Commit {
	static function create(repo:nodegit.Repository, update_ref:String, author:nodegit.Signature, committer:nodegit.Signature, message_encoding:String, message:String, tree:nodegit.Tree, parent_count:Float, parents:Array<Dynamic>):nodegit.Oid;
	static function createV(id:nodegit.Oid, repo:nodegit.Repository, update_ref:String, author:nodegit.Signature, committer:nodegit.Signature, message_encoding:String, message:String, tree:nodegit.Tree, parent_count:Float):Float;
	static function lookup(repo:nodegit.Repository, id:Dynamic):js.Promise<nodegit.Commit>;
	static function lookupPrefix(repo:nodegit.Repository, id:nodegit.Oid, len:Float):js.Promise<nodegit.Commit>;
	function amend(update_ref:String, author:nodegit.Signature, committer:nodegit.Signature, message_encoding:String, message:String, tree:nodegit.Tree):nodegit.Oid;
	function author():nodegit.Signature;
	function committer():nodegit.Signature;
	function date():Dynamic;
	function free():Void;
	function getDiff(callback:Dynamic):js.Promise<Array<nodegit.Diff>>;
	function getDiffWithOptions(options:nodegit.Object, callback:Dynamic):js.Promise<Array<nodegit.Diff>>;
	function getEntry(path:String):js.Promise<nodegit.TreeEntry>;
	function getParents(limit:Dynamic, callback:Dynamic):js.Promise<Array<nodegit.Commit>>;
	function getTree():js.Promise<nodegit.Tree>;
	function headerField(field:String):js.Promise<nodegit.Buf>;
	function history():Dynamic;
	function id():nodegit.Oid;
	function message():String;
	function messageEncoding():String;
	function messageRaw():String;
	function nthGenAncestor(n:Float):js.Promise<nodegit.Commit>;
	function owner():nodegit.Repository;
	function parent(n:Float):js.Promise<nodegit.Commit>;
	function parentId(n:Float):nodegit.Oid;
	function parentcount():Float;
	function parents(callback:Dynamic):Array<nodegit.Oid>;
	function rawHeader():String;
	function sha():String;
	function summary():String;
	function time():Float;
	function timeMs():Float;
	function timeOffset():Float;
	function toString():String;
	function tree(tree_out:nodegit.Tree):Float;
	function treeId():nodegit.Oid;
}